version: '3.8'

services:
  frontend:
    container_name: frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production
    networks:
      - pks-net
    restart: unless-stopped

networks:
  pks-net:
    external: true
